config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, :skip => [:registrations]
  as :account do
    get  'registration' => 'devise/registrations#new',    :as => :account_registration
    post 'registration' => 'devise/registrations#create', :as => :new_account_registration
    get  'log_out'      => 'devise/sessions#destroy',     :as => :log_out
    get  'log_in'       => 'devise/sessions#new',         :as => :log_in
  end

  root 'news#index'
  get  'news/:id'      => 'news#view',   as: :view
  get  'post/edit/:id' => 'news#edit',   as: :edit_post
  get  'post/new'      => 'news#new',    as: :create_post
  post 'post/new'      => 'news#create'
  post 'post/edit/:id' => 'news#update'
  get 'shop/:id' => 'shop#view'

end

app/models/access.rb
class Access < ActiveRecord::Base
	belongs_to :account
	self.table_name = "account_access"
end

app/models/account.rb
class Account < ActiveRecord::Base
  	# Devise modules
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, 
           :validatable, :encryptable

    # Trinity Core db table name
	self.table_name = "account"

	has_one :access, :foreign_key => "id"
	before_save :set_username

	validates :email, presence: true, uniqueness: true, confirmation: true, length: { in: 6..20 }
	validates :password, confirmation: true
	validates_length_of :password, in: 6..16, on: :create
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

	# Set username as email
	def set_username
		unless email.blank?
			self.username = email
		else
			false
		end
	end

	# Passing email as salt to custom encryptor
	def password_salt
  		email
	end

  	def password_salt=(value)
  		email
  	end

  	# Using auth db field 'sha_pass_hash' instead of devise 'encrypted_password'
  	def encrypted_password
    	return sha_pass_hash
  	end

  	def encrypted_password=(value)
  		self.sha_pass_hash = value
  	end

end

app/models/character.rb
class Character < ActiveRecord::Base
	establish_connection("characters_db").connection

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.
# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	helper_method :current_user, :players_online, :server_status

	private

	def current_user
	  @current_user ||= Account.find(session[:user_id]) if session[:user_id]
	end

	def players_online
		@players_online ||= Character.where(online: 1).count
	end

	def connect(host = Settings.server.ip, port = Settings.server.port, timeout = 2)
	  # Convert the passed host into structures the non-blocking calls
	  # can deal with
	  addr = Socket.getaddrinfo(host, nil)
	  sockaddr = Socket.pack_sockaddr_in(port, host)

	  Socket.new(Socket.const_get(addr[0][0]), Socket::SOCK_STREAM, 0).tap do |socket|
	    socket.setsockopt(Socket::IPPROTO_TCP, Socket::TCP_NODELAY, 1)

	    begin
	      # Initiate the socket connection in the background. If it doesn't fail 
	      # immediatelyit will raise an IO::WaitWritable (Errno::EINPROGRESS) 
	      # indicating the connection is in progress.
	      socket.connect_nonblock(sockaddr)

	    rescue IO::WaitWritable
	      # IO.select will block until the socket is writable or the timeout
	      # is exceeded - whichever comes first.
	      if IO.select(nil, [socket], nil, timeout)
	        begin
	          # Verify there is now a good connection
	          socket.connect_nonblock(sockaddr)
	        rescue Errno::ECONNREFUSED
	          socket.close
	          return false
	        rescue Errno::EISCONN
	          # Good news everybody, the socket is connected!
	        rescue
	          # An unexpected exception was raised - the connection is no good.
	          socket.close
	          return false
	        end
	      else
	        # IO.select returns nil when the socket is not ready before timeout 
	        # seconds have elapsed
	        socket.close
	        return false
	      end
	    end
	  end
	end

	def server_status
		if(Settings.server.lastUpdate.nil?)
			Settings.lastUpdate = Time.current
			check_connection
		else
			if(Time.current - Time.parse(Settings.server.lastUpdate) > Settings.server.diff)
				Settings.lastUpdate = Time.now
				check_connection
			else
				Settings.server.lastUpdateResult
			end
		end
	end

	def check_connection
		connection = connect(Settings.server.ip, Settings.server.port, 2)

		if !connection
			Settings.server.lastUpdateResult = "offline"
		else
			Settings.server.lastUpdateResult = "online"
		end
	end


end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
  	@news = News.all().order("id DESC")
  end

  def view
  	@post = News.find_by(id: params[:id])

  	if(@post.blank?) 
  		redirect_to root_path
	end
  end

  def edit
  	if current_user && current_user.access.gmlevel > Settings.roles[:edit_post]
  		@post = News.find_by(id: params[:id])

	  	if @post.blank?
	  		redirect_to root_path
		end
	else
  		redirect_to root_path
	end
  end

  def new
  	@post = News.new()
  end

  def create
  	@post = News.new(post_params)

  	if @post.save
  		flash.now[:success] = "Post created successfully"
	else
		flash.now[:error] = "Please, check your data"
	end
		render 'new'
  end

  def update
	@post = News.find(params[:id])

  	if @post.update(post_params)
		redirect_to view_path(@post)
	else
		render 'edit'
	end
  end

  private

  def post_params
	params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_left.html.erb
<div id="left">
    <div id="slide-bg">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
                <li data-target="#myCarousel" data-slide-to="4"></li>
                <li data-target="#myCarousel" data-slide-to="5"></li>
            </ol>
            <div class="carousel-inner">
                <div class='item active diapo1' style='background-image:url("http://<%= Settings.more.site %>/assets/img/left/slide/612.png");'>
                    <div class='container'>
                        <div class='carousel-caption'>
                            <span class='slide-title'>Go test 6.1.2</span>
                            <br/>
                            Come & try the new 6.1.2 version on Ashran
                        </div>
                    </div>
                </div>
                <div class='item diapo1' style='background-image:url("http://<%= Settings.more.site %>/assets/img/left/slide/drov.png");'>
                    <div class='container'>
                        <div class='carousel-caption'>
                            <span class='slide-title'>Drov the Ruiner</span>
                            <br/>
                            Drov the Ruiner, the one who makes the earth shake and carves a swath of devastation!
                        </div>
                    </div>
                </div>
                <div class='item diapo1' style='background-image:url("http://<%= Settings.more.site %>/assets/img/left/slide/slider_bloodmaul.png");'>
                    <div class='container'>
                        <div class='carousel-caption'>
                            <span class='slide-title'>Bloodmaul mines</span>
                            <br/>
                            Go fight the Ogres of Bloodmaul !
                        </div>
                    </div>
                </div>
                <div class='item diapo1' style='background-image:url("http://<%= Settings.more.site %>/assets/img/left/slide/slider_garrisons.png");'>
                    <div class='container'>
                        <div class='carousel-caption'>
                            <span class='slide-title'>GARRISONS</span>
                            <br/>
                            Build your garrison and train your followers !
                        </div>
                    </div>
                </div>
                <div class='item diapo1' style='background-image:url("http://<%= Settings.more.site %>/assets/img/left/slide/slider_ashran2.png");'>
                    <div class='container'>
                        <div class='carousel-caption'>
                            <span class='slide-title'>ASHRAN ZONE</span>
                            <br/>
                            Beat your enemies in this new PvP area !
                        </div>
                    </div>
                </div>
                <div class='item diapo1' style='background-image:url("http://<%= Settings.more.site %>/assets/img/left/slide/slider_skyreach.png");'>
                    <div class='container'>
                        <div class='carousel-caption'>
                            <span class='slide-title'>SKYREACH</span>
                            <br/>
                            Go fight Anjit, Araknath, Rukhran and High Sage Viryx !
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <article>
        <%= yield %>
        </article>
    </div>
</div>

app/views/layouts/_loginForm.html.erb
<%= form_for(:account, :url => session_path(:account)) do |f| %>
	<%= content_tag(:div, id: 'user') do %>
		<%= email_field_tag :email, params[:email], :id => 'pseudo' %>
	<% end %>
	<%= content_tag(:div, id: 'password') do %>
		<%= password_field_tag :password,'', :id => 'pass' %>
	<% end %>
	<%= content_tag(:div, id: 'connexion') do %>
		<%= submit_tag "LOG IN", :id => 'connect' %>
	<% end %>
	<%= link_to "Password forgotten ?", new_password_path(:account), :class => 'link' %>
    <br>
    <%= link_to 'Create an account', registration_path(:account), :class => 'link' %>
<% end %>

app/views/layouts/_memberArea.html.erb
<div id="membership-connected">
	Hello, <span class="important"><%= current_account.username %></span>
    <br/>
		You currently have 
    <span style='color: #A12009;'>
        <b>0</b>
    </span> points.
    <br/>
    
    <ul>
        <% if(current_account.access && current_account.access.gmlevel >= 3) %>
        <li>
            <%= link_to 'Add post', create_post_path %>
        </li>
        <% end %>
        <li>
            <a href="#"> Account management </a>
        </li>
        <li>
            <a href="#" class='buy-points-popup'> Buy points </a>
        </li>
        <li>
            <a href="#"> Vote for us </a>
        </li>
    </ul>
    <%= link_to "Disconnection", log_out_path, :class=> "link" %>
</div>

app/views/layouts/_right.html.erb
<div id="right">
	<div id="social-bg">
		<ul>
			<li class="youtube">
			<a href="https://www.youtube.com/watch?v=wGW7lSDkyUk"></a>
			</li>
			<li class="facebook">
			<a href="https://www.facebook.com/pages/Ashran-International/843684365676292"></a>
			</li>
			<li class="twitter">
			<a href="https://twitter.com/AshranServer"></a>
			</li>
		</ul>
	</div>
	<div id="join-bg">
		<div id="join" class="genericbutton">
			<a href="http://<%= Settings.more.site %>/site/register">Launcher </a>
		</div>
	</div>
	<div id="membership">
		<div id="membership-top">
			<div id="english-flag" class='flag-active'>
				<a href="http://<%= Settings.more.site %>/us">
				</a>
			</div>
			<div id="french-flag">
				<a href="https://<%= Settings.more.site %>/fr">
				</a>
			</div>
			<div id="german-flag">
				<a href="http://<%= Settings.more.site %>/de">
				</a>
			</div>
			<div id="spanish-flag">
				<a href="http://<%= Settings.more.site %>/es">
				</a>
			</div>
			<div id="russian-flag">
				<a href="http://<%= Settings.more.site %>/ru">
				</a>
			</div>
		</div>
		<div id="membership-middle">
			<% if account_signed_in? %>
		    	<%= render 'layouts/memberArea' %>
			<% else %>
		    	<%= render 'layouts/loginForm' %>
		    <% end %>
		</div>
		<div id="membership-end">
		</div>
	</div>
	<div id="realm">
		<div id="realm-top">
			<span class="title"> REALM </span>
		</div>
		<div id="realm-middle">
			<div id="content">
				<span class="realm-title"><%= Settings.server.name %></span>
				<div id="divider">
				</div>
				<span class="player-title"> Players </span>
				<span class="player-number"><span class="<%= server_status %>"> <%= players_online %> / <%= Settings.server.max_players %></span></span>
				<br/>
				<div id="realm-bar">
					<div id="progress" style="width:<%= (players_online * 100) / Settings.server.max_players %>%;">
					</div>
				</div>
			</div>
		</div>
		<div id="realm-end">
		</div>
	</div>
	<div id="vote" class="genericbutton">
		<a href="http://<%= Settings.more.site %>/vote"> Vote for us </a>
	</div>
	<div id="buypoints" class="genericbutton" class="buy-points-popup">
		<a href="javascript:void(0)" class="buy-points-popup">Buy points</a>
		</a>
	</div>
	<div id="shop" class="genericbutton">
		<a href="http://<%= Settings.more.site %>/shop"> VISIT OUR SHOP </a>
	</div>
	<div id="support" class="genericbutton">
		<a href="http://<%= Settings.more.site %>/support"> Shop support </a>
	</div>
	<div id="faq" class="genericbutton">
		<a href="http://<%= Settings.more.site %>/faq"> Questions </a>
	</div>
	<div id="forum" class="genericbutton">
		<a href="http://forum.ashran.com/"> FORUM </a>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Ash-WoW</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<script type="text/javascript" src="http://static.wowhead.com/widgets/power.js"></script>
  	<%= csrf_meta_tags %>
</head>
<body>
<div class="page">
	<div id="main">
		<header>
			<div id="logo">
				<a href="#"></a>
			</div>
		</header>
		<div id="body">
			<div id="body-top">
			</div>
			<div id="body-middle">
				<%= render 'layouts/left' %>
				<%= render 'layouts/right' %>
			</div>
		</div>
		<footer></footer>
	</div>
</div>
</body>
</html>

app/views/news/edit.html.erb
<div id="contenu">
  <div id="contenu-top2">
    <div id="title">
      Registration            
    </div>
  </div>
  <div id="contenu-middle">
  	<% flash.each do |key, value| %>
	  <%= content_tag :div, value, class: "flash #{key}" %>
	<% end %>
	<% if @post.errors.any? %>
		<ul class="errors">
			<% for message in @user.errors.full_messages %>
				<li>* <%= message %> </li>
			<% end %>
		</ul>
	<% end %>
    <span class="text">
    <%= form_for(:post, :html => { id: 'inscription' } ) do |f| %>
    	<%= f.label :title, class: 'edit-post', style: 'display: block; height: 33.5px; width: 80px; padding-top: 9px; float: left; text-align: left;'  %>
    	<%= content_tag(:div, id: 'input', style: 'margin-left: 80px;' ) do %>
    		<%= f.text_field :title, class: 'text_form' %>
    	<% end %>

    	<%= f.label :content, style: 'display: block; height: 33.5px; width: 80px; padding-top: 9px; text-align: left; float: left;' %>
        <%= content_tag(:div, id: 'textarea-input', style: 'margin-bottom: 7px; padding-left: 4px; padding-top: 4px;') do %>
        	<%= f.text_area :content, style: 'width: 500px; max-width: 550px; text-align: left; float: left; height: 150px;' %>
        <% end %>

        <%= content_tag(:div, id: 'validate') do %>
            <%= f.submit :Save, id: 'valide' %>
        <% end %>
    <% end %>
       
    </span>
  </div>
</div>

app/views/news/index.html.erb
<% if Settings.welcome.enabled %> 
	<div id="welcome">
		<div id="text">
			<span class="title"> <%= Settings.welcome.title %> </span>
			<br>
			<span class="text"> <%= Settings.welcome.message %> </span>
		</div>
	</div>
<% end %>
<% @news.each do |post| %>
<div id="contenu">
	<div id="contenu-top">
		<div id="title">
			<%= link_to post.title, view_path(post) %>
		</div>
		<div id="date">
                <%= post.updated_at.to_formatted_s(:short) %>
        </div>
	</div>
	<div id="contenu-middle">
		<span class="text">
		<%= truncate_html(post.content, length: 440, omission: "...") %>
		</span>
	</div>
	<div id="contenu-end">
	</div>
</div>
<% end %>

app/views/news/new.html.erb
<div id="contenu">
  <div id="contenu-top2">
    <div id="title">
      Add post            
    </div>
  </div>
  <div id="contenu-middle">
  	<% flash.each do |key, value| %>
	  <%= content_tag :div, value, class: "flash #{key}" %>
	<% end %>
	<% if @post.errors.any? %>
		<ul class="errors">
			<% for message in @user.errors.full_messages %>
				<li>* <%= message %> </li>
			<% end %>
		</ul>
	<% end %>
    <span class="text">
    <%= form_for(:post, :html => { id: 'inscription' } ) do |f| %>
    	<%= f.label :title, class: 'edit-post', style: 'display: block; height: 33.5px; width: 80px; padding-top: 9px; float: left; text-align: left;'  %>
    	<%= content_tag(:div, id: 'input', style: 'margin-left: 80px;' ) do %>
    		<%= f.text_field :title, class: 'text_form' %>
    	<% end %>

    	<%= f.label :content, style: 'display: block; height: 33.5px; width: 80px; padding-top: 9px; text-align: left; float: left;' %>
        <%= content_tag(:div, id: 'textarea-input', style: 'margin-bottom: 7px; padding-left: 4px; padding-top: 4px;') do %>
        	<%= f.text_area :content, style: 'width: 500px; max-width: 550px; text-align: left; float: left; height: 150px;
            background-color: rgb(17, 16, 15); border: 1px solid #24211E; border-radius: 3px; padding: 5px;' %>
        <% end %>

        <%= content_tag(:div, id: 'validate') do %>
            <%= f.submit :Submit, id: 'valide' %>
        <% end %>
    <% end %>
       
    </span>
  </div>
</div>

app/views/news/view.html.erb
<div id="contenu">
	<div id="contenu-top">
		<div id="title">
			<%= @post.title %>
		</div>
		<div id="date">
            <%= @post.updated_at.to_formatted_s(:short) %>
        </div>
	</div>
	<div id="contenu-middle">
		<span class="text">
		<%= @post.content %>
		</span>
	</div>
	<div id="contenu-end">
	</div>
</div>